name: Build and Deploy to GitHub Pages

on:
  push:

jobs:

  build-and-deploy:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-gh-pages-deployment.yml@58-allow-the-use-of-env-file-to-frontend-static-deployment-workflows
    with:
      node-version: 18
      publish-dir: ./build
      cache-dependency-path: .
    secrets: inherit
